feat: add better guides for quickstart
armadaproject/armada-operator pull request #292
Opened 2023-11-03 13:18 UTC by dejanzele

2023-11-03 13:43 UTC, dave-gantenbein requested changes
Can you remove references to Kubecon from this so its more evergreen?

2023-11-03 15:50 UTC, richscott reviewed
I saw a typo, but it's not a deal-breaker. I agree that the KubeCon references should probably be removed. 

Note that Lookout V1 images are no longer being built, so it's good that this PR doesn't update to latest versions of the images. I have a bunch of changes to remove all references to Lookout V1, and update to latest numbered versions of all images, but that can wait until after this PR is merged.

2023-11-03 15:50 UTC, richscott commented on README.md
> +which provides a reconcile function responsible for synchronizing resources untile the desired state is reached on the cluster
Typo: `untile` should be `until` ?

2024-05-09 17:42 UTC, richscott submitted a review, later dismissed

2024-05-09 18:19 UTC, dave-gantenbein approved these changes
lgtm

2024-05-09 18:26 UTC, merged